apiVersion: v2
name: kube-prometheus-stack
version: 1.0.0
description: Prometheus monitoring stack for Kubernetes
dependencies:
  - name: kube-prometheus-stack
    version: "65.8.1"
    repository: https://prometheus-community.github.io/helm-charts
